### ISSUE TITLE
Contribute to the Haxe Code Cookbook?

### ISSUE THREAD

**Issue by anissen** [r3d9u11/haxe-basics#1]
It's a great and very extensive collection of samples and snippets you have here! 👍 

Maybe consider contributing some of them to the [Haxe Code Cookbook](http://code.haxe.org/)? The repository with contribution guidelines is available at [HaxeFoundation/code-cookbook](https://github.com/HaxeFoundation/code-cookbook). (Pinging @MarkKnol)

**Comment by R3D9477** [comment]
@anissen Yes, of course! It would be cool and help others to find a some solution
